### ISSUE TITLE
Library needs a way to access the response headers from the request

### ISSUE THREAD

**Issue by matthewpennell** [eveseat/eseye#14]
For several of the ESI endpoints we need access to the response headers, e.g. market order lists, wallet transactions, etc. are all returned paginated. The first request will return an `X-Pages` header containing the total number of pages, and then we need to loop through and make further requests, appending a `page=n` parameter to the URL.

Since the current implementation automatically converts the response into an object, there is no way to retrieve the headers without doing a separate request using curl or similar.

**Comment by leonjza** [comment]
Will *definitely* add this. There are some other interesting headers that will be useful too.

**Comment by rmatulis** [comment]
I have created a very basic way that headers are returned and accessed via a method the same as the error message is.
I have set it up so it will return the headers in an array.
This can be accessed via a method to get all the headers or specific ones.

@leonjza are you open to a pull request on this?

**Comment by leonjza** [comment]
Absolutely @clonerworks. I have been migrating SeAT to consume ESI endpoints using this library the last week and also have the requirement to access these headers now. Ill probably also give this a bash pretty soon too, but I think it would be nice to have the `EsiResponse` object have the response headers in an `ArrayObject`. Maybe something like `$response->headers->header_name`.

Since pagination is such an important part, even that could be parsed as a separate entity available on the response object.

**Comment by leonjza** [comment]
I went ahead and did some work on this as I needed it now :)

Since 35553bd4324, there are four new properties available on an `EsiResponse` object. Those are: `headers`, `raw_headers`, `error_limit` , and `pages` ([ref](https://github.com/eveseat/eseye/blob/35553bd432452266d4bce3a217719c72615716b3/src/Containers/EsiResponse.php#L43-L58)). I am guessing they are relatively self explanatory based on their names.

Since c6268b1c341cc94, a new `page()` helper was added where you can specify the page number to retrieve when you `invoke()` an ESI request. An example use of this is:

```php

$response = $esi->setQueryString(['order_type' => 'sell'])
            ->page(2)   // page two of the results please!
            ->invoke('get', '/markets/{region_id}/orders/', [
                'region_id' => 10000001,
            ]);

print($response->error_limit);  // output 100 for example
print($response->pages);        // output 2 for example
```

**Comment by leonjza** [comment]
Also, tagged in 0.0.11.

**Comment by rmatulis** [comment]
@leonjza brilliant work. Thank you. Sorry I couldn't help quicker I have been working all of this weekend.
