### ISSUE TITLE
Implement If-None-Match

### ISSUE THREAD

**Issue by leonjza** [eveseat/eseye#33]
https://developers.eveonline.com/blog/article/esi-etag-best-practices

**Comment by warlof** [comment]
addressed in eveseat/eseye#34

**Comment by Eingang** [comment]
Do we need to do something to make it honour it, like track/store the eTags and include the last known one in our requests with a "If-None-Match" match header? 

I'm wondering because, unlike my previous XML-based library, Notification ESI calls are returning every single Notification I have every single time, even if nothing has changed. It's a bit odd!

**Comment by warlof** [comment]
Check pr upper

**Comment by leonjza** [comment]
I still need to work through this PR still, but the end result in Eseye will be an extra property on the `EsiResponse` object with the Etag value, and if it matches based on a cached value.
