### ISSUE TITLE
Update Guzzle to Allow for Implementation with Laravel 8

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/eseye#67]
Any idea when guzzle will be updated to allow this to be implemented with Laravel 8 since Laravel 8 requires at guzzle version 7.0.1?

**Comment by warlof** [comment]
Hi,

Probably not before next Laravel LTS version if I have to handle the update.
However, if you want to put some time in it and send a pull request, it can be added and depending on applied changes, either tags as 2 or 3.

At worse, you should be able to implement a Guzzle 7 custom fetcher and use it in config instead of the ship one :)

**Comment by warlof** [comment]
available since 2.4.0 - thanks to @gordonzero who took time to manage the update
