### ISSUE TITLE
Token Expired

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/eseye#68]
When I pull a token from the database, which only gets used once per hour, and I create the EsiAuthenticationContainer, I get an exception stating the token has expired.  How can I utilize the refresh token with Eseye in order to get a fresh access token?  I create the container as shown below:
```
//insert_at and expires_in are integers in unix timestamp
$expires = $token->inserted_at + $token->expires_in;

            $authentication = new EsiAuthentication([
                'client_id' => $config['client_id'],
                'secret' => $config['secret'],
                'refresh_token' => $token->refresh_token,
                'access_token' => $token->access_token,
                'token_expires' => $expires,
            ]);

            //Setup the esi variable
            $esi = new Eseye($authentication); 
```

```
Jose\Component\Checker\InvalidClaimException

  The token expired.

  at vendor/web-token/jwt-checker/ExpirationTimeChecker.php:53
    49|         if (!is_float($value) && !is_int($value)) {
    50|             throw new InvalidClaimException('"exp" must be an integer.', self::NAME, $value);
    51|         }
    52|         if (time() > $value + $this->allowedTimeDrift) {
  > 53|             throw new InvalidClaimException('The token expired.', self::NAME, $value);
    54|         }
    55|     }
    56|
    57|     public function supportedClaim(): string
```

**Comment by warlof** [comment]
Hi,

Seems related to controls applied on the provided token.
Normally, Eseye is applying basic checks and updating any expired token before first call using the provided refresh token itself.

Your flow doesn't seem different than the one applied in SeAT - except scopes.

Be sure you provide an UTC date/time to `token_expires`.

Do you have this issue if you're providing a scopes entry in the container ?
~~Also, a full stack would be helpful here, since the provided code isn't triggering it :P~~
Nvm, provide scopes in your authentication containers - if none, use `publicData`

Or, alternatively, do not provide an authentication container.

The underlined reason is because if you do not provide any scopes, Eseye will attempt to decode those from provided token - and to do so, it needs to load the token - which trigger validity check rules from JWT library.

https://github.com/eveseat/eseye/blob/e1e310592ea03aa8a68728d8c15d7f04cf29f957/src/Fetchers/GuzzleFetcher.php#L391-L392

When no token information are provided, Eseye assume it's a public call and skip all the token flow.

https://github.com/eveseat/eseye/blob/e1e310592ea03aa8a68728d8c15d7f04cf29f957/src/Fetchers/GuzzleFetcher.php#L385-L386
